In [81]:
import numpy as np
import pandas as pd
from transaction_dates import *
from imiona import *
from collections import Counter
from samochody import *
from czesci import *

# Pracownicy

In [82]:
birth_dates_lims = [1960, 1995]
begining_date = "2014-01-01"
end_date = "2018-01-01"

def rind(a, b):
    return np.random.randint(a, b)

jobs_list = np.array(["menadżer", "sprzedawca", "mechanik", "pomocnik mechanika", 
                       "diagnosta samochodowy", "sprzątający", "informatyk", "księgowy"])
jobs_amount = np.array([1, rind(2, 5), rind(3, 6), rind(1, 3),
                        rind(1, 3), rind(1, 3), rind(1, 3), rind(0, 2)])
fixed_jobs = np.array([0, 1, 2, np.sum(jobs_amount[:2]), np.sum(jobs_amount[0:6])]) # zaczynamy z szefem, dwoma sprzedawcami i mechanikiem

employment_dates = random_transaction_dates(begining_date, end_date, np.sum(jobs_amount))
employment_dates[fixed_jobs] = begining_date  

wages_lims = [(60, 75), (45, 60), (45, 60), (35, 45),
              (47, 60), (35, 40), (40, 60), (40, 53)]

employees_df = pd.DataFrame(columns=["id", "imię", "nazwisko", "data_urodzenia", "pesel",
                                     "miasto", "adres", "telefon", "email", "data_zatrudnienia",
                                     "data_zwolnienia", "stanowisko", "płaca[zł/h]"])
for (i, job) in enumerate(jobs_list):
    c = 0
    for j in range(jobs_amount[i]):
        employment_date = employment_dates[np.sum(jobs_amount[:i]) + j]
        if np.random.rand() <= 0.5:
            first_name, last_name = random_name_man()
            pesel, birth_date = random_pesel_date_man(birth_dates_lims)
            sex = "M"
            city = random_city(prob=0.7)
            address = random_street()
            phone = random_phone()
            #email = random_email(first_name, last_name, birth_date[-4:])
            email = employee_email(first_name, last_name)
            employment_date = employment_dates[np.sum(jobs_amount[:i]) + j]
            wage = np.random.choice(np.arange(wages_lims[i][0], wages_lims[i][1], 0.1))
        else:
            first_name, last_name = random_name_woman()
            pesel, birth_date = random_pesel_date_woman(birth_dates_lims)
            sex = "K"
            city = random_city(prob=0.7)
            address = random_street()
            phone = random_phone()
            #email = random_email(first_name, last_name, birth_date[-4:])
            email = employee_email(first_name, last_name)
            employment_date = employment_dates[np.sum(jobs_amount[:i]) + j]
            wage = np.random.choice(np.arange(wages_lims[i][0], wages_lims[i][1], 0.1))
        if np.random.rand() <= (jobs_amount[i]-1)/10 * 1/(1+c):
            dismissal_date = random_transaction_dates(str(employment_date), end_date, 1)[0]
            c += 1
        else:
            dismissal_date = None

        employees_df.loc[np.sum(jobs_amount[:i]) + j] = [0, first_name, last_name, birth_date, pesel,
                                                         city, address, phone, email, employment_date,
                                                         dismissal_date, job, wage]

employees_df = employees_df.sort_values(by="data_zatrudnienia")   
employees_df["id"] =  np.arange(1, len(employees_df)+1)

In [83]:
employees_df

id       imię      nazwisko data_urodzenia        pesel        miasto  \
0    1   Leokadia   Kapuścińska     12/10/1980  80101212942        Szubin   
1    2      Filip          Fiec     13/08/1965  65081370176       Wrocław   
2    3   Gabriela         Moryń     12/08/1960  60081216424      Hajnówka   
5    4     Henryk     Jankowski     02/05/1988  88050211858       Wrocław   
15   5  Sebastian  Andrzejewski     16/12/1987  87121616235        Rybnik   
3    6     Bożena      Grodecka     27/05/1968  68052758586      Sulechów   
4    7      Artur   Grzegorczyk     13/07/1976  76071307375    Czerwieńsk   
6    8      Marek       Sobczak     09/09/1982  82090990111      Koszalin   
7    9   Wojciech          Wilk     29/09/1993  93092961599       Wrocław   
8   10  Stanisław     Marcjanik     04/05/1976  76050472131       Wrocław   
9   11      Beata  Brejnakowska     21/08/1987  87082182604       Wrocław   
10  12      Maiia      Kowalska     11/07/1974  74071131783       Wrocław   
11  13    Justyna      Lipowska     02/02/1960  60020277862       Wrocław   
12  14  Sebastian    Czachorski     31/07/1962  62073156178       Wrocław   
13  15  Krzysztof        Florek     25/02/1995  95022556712  Zielona Góra   
14  16    Bartosz         Wężyk     13/06/1992  92061334677       Wrocław   
16  17    Urszula     Radlińska     20/11/1961  61112018462       Wrocław   
17  18    Viviane      Góreczny     28/01/1995  95012847680       Wrocław   

                             adres      telefon  \
0                 ul. Górska 26/17  48680837445   
1                  ul. Borki 77/22  48036561806   
2               ul. Elbląska 48/43  48188418997   
5                ul. Jerzyka 81/31  48431168750   
15                 ul. Ludowa 98/6  48131030714   
3   ul. III Dywizji Piechoty 59/19  48725678254   
4                    ul. Łanowa 75  48071456709   
6          ul. Jana Pawła II 45/42  48825493021   
7               ul. Jana Cybisa 92  48294037662   
8          ul. Armii Krajowej 10/8  48812657546   
9                   ul. Rzeczna 86  48316845751   
10                ul. Łucznicza 90  48700635160   
11             ul. Spacerowa 98/36  48737321143   
12                  ul. Leśna 32/4  48955877931   
13            ul. Jastrzębia 30/50  48761001800   
14              ul. Jagodowa 16/10  48973708994   
16               ul. Poselska 28/3  48142671558   
17              ul. Strumień 56/23  48011286874   

                             email data_zatrudnienia data_zwolnienia  \
0     leokadia.kapuscinska@kuba.pl        2014-01-01            None   
1               filip.fiec@kuba.pl        2014-01-01      2015-09-03   
2           gabriela.moryn@kuba.pl        2014-01-01            None   
5         henryk.jankowski@kuba.pl        2014-01-01            None   
15  sebastian.andrzejewski@kuba.pl        2014-01-01            None   
3          bozena.grodecka@kuba.pl        2014-04-05            None   
4        artur.grzegorczyk@kuba.pl        2014-04-10            None   
6            marek.sobczak@kuba.pl        2015-06-27      2016-04-28   
7            wojciech.wilk@kuba.pl        2015-09-13            None   
8      stanislaw.marcjanik@kuba.pl        2015-10-17            None   
9       beata.brejnakowska@kuba.pl        2015-10-23      2016-10-06   
10          maiia.kowalska@kuba.pl        2016-10-02            None   
11        justyna.lipowska@kuba.pl        2016-12-11            None   
12    sebastian.czachorski@kuba.pl        2017-01-31            None   
13        krzysztof.florek@kuba.pl        2017-02-09            None   
14           bartosz.wezyk@kuba.pl        2017-03-24            None   
16       urszula.radlinska@kuba.pl        2017-09-14            None   
17        viviane.goreczny@kuba.pl        2017-10-26            None   

               stanowisko  płaca[zł/h]  
0                menadżer         61.5  
1              sprzedawca         51.1  
2              sprzedawca         50.9  
5                mechanik         52.

# Transakcje

In [84]:
no_transactions = 2000
begining_buy = 20

dates = random_transaction_dates("2014-01-01", "2020-12-31", no_transactions)

In [85]:
client_ids = np.zeros(len(dates), dtype=int) # array with client ids for table with transactions

j = 1
for i in range(len(dates)):
    prob = i/(2*len(dates))
    if np.random.rand() <= prob:
        client_ids[i] = np.random.choice(np.unique(client_ids[:i]))
    else:
        client_ids[i] = j
        j += 1

In [86]:
car_ids = np.zeros(len(dates), dtype=int) # array with car ids for table with transactions
car_ids[:begining_buy] = np.arange(1, 21)

client_ids = np.zeros(len(dates), dtype=int) # array with client ids for table with transactions
client_ids[:begining_buy] = np.arange(1, 21)

transactions_types = np.zeros(len(dates))

clients_cars = {}
our_cars = np.arange(1, 21).tolist()

jp = 21
jc = 21
for i in range(20, len(dates)):
    weights = np.array([1.5*len(clients_cars)/max(1, len(our_cars)) , len(our_cars)*50, len(clients_cars)/(5*max(1, len(our_cars)))])
    weights = weights/np.sum(weights)
    transaction_type = np.random.choice(np.arange(3), p=weights) # 0-buy, 1-sell, 2-service
    transactions_types[i] = transaction_type
    if transaction_type == 0:
        prob = i/(2*len(dates)) 
        if np.random.rand() <= prob: #client that already is in database
            client_ids[i] = np.random.choice(np.unique(client_ids[:i]))
            if client_ids[i] in clients_cars and np.random.rand() <= 0.6 and len(clients_cars[client_ids[i]]) >= 1:
                car_ids[i] = np.random.choice(clients_cars[client_ids[i]])
                clients_cars[client_ids[i]].remove(car_ids[i])
            else:
                car_ids[i] = jc
                jc += 1
            our_cars.append(car_ids[i])
        else:
            client_ids[i] = jp
            car_ids[i] = jc
            our_cars.append(car_ids[i])
            jp += 1
            jc += 1

    if transaction_type == 1:
        prob = i/(2*len(dates))
        if np.random.rand() <= prob: #client that already is in database
            client_ids[i] = np.random.choice(np.unique(client_ids[:i]))
            car_ids[i] = np.random.choice(our_cars)
            if client_ids[i] in clients_cars:
                clients_cars[client_ids[i]].append(car_ids[i])
            else:
                clients_cars[client_ids[i]] = [car_ids[i]]
            our_cars.remove(car_ids[i])
        else:
            client_ids[i] = jp
            car_ids[i] = np.random.choice(our_cars)
            clients_cars[client_ids[i]] = [car_ids[i]]
            our_cars.remove(car_ids[i])
            jp += 1
    
    if transaction_type == 2:
        prob = i/(2*len(dates))
        if np.random.rand() <= prob: #client that already is in database
            client_ids[i] = np.random.choice(np.unique(client_ids[:i]))
            if client_ids[i] in clients_cars:
                if np.random.rand() <= 0.6 and len(clients_cars[client_ids[i]]) >= 1:
                    car_ids[i] = np.random.choice(clients_cars[client_ids[i]])
                else:
                    car_ids[i] = jc
                    clients_cars[client_ids[i]].append(car_ids[i])
                    jc += 1
            else:
                car_ids[i] = jc
                clients_cars[client_ids[i]] = [car_ids[i]]
                jc += 1
        else:
            client_ids[i] = jp
            car_ids[i] = jc
            clients_cars[client_ids[i]] = [car_ids[i]]
            jp += 1
            jc += 1

In [87]:
buy_indexes = np.where(transactions_types == 0)
sell_indexes = np.where(transactions_types == 1)
service_indexes = np.where(transactions_types == 2)

In [88]:
transaction_dates_buy = dates[buy_indexes]
transaction_dates_sell = dates[sell_indexes]
transaction_dates_service = dates[service_indexes]

client_ids_buy = client_ids[buy_indexes]
client_ids_sell = client_ids[sell_indexes]
client_ids_service = client_ids[service_indexes]

car_ids_buy = car_ids[buy_indexes]
car_ids_sell = car_ids[sell_indexes]
car_ids_service = car_ids[service_indexes]

In [89]:
buy_employee_id = np.zeros(len(transaction_dates_buy))

for i in range(len(transaction_dates_buy)):
    filter1 = employees_df["stanowisko"] == "sprzedawca"
    filter2 = employees_df["data_zatrudnienia"] <= transaction_dates_buy[i]
    filter3 = pd.notna(employees_df["data_zwolnienia"])
    filter4 = employees_df["data_zwolnienia"] < transaction_dates_buy[i]
    buy_employee_id[i] = np.random.choice(employees_df['id'][filter1 & filter2 & ~(filter3 & filter4)])

In [90]:
sell_employee_id = np.zeros(len(transaction_dates_sell))

for i in range(len(transaction_dates_sell)):
    filter1 = employees_df["stanowisko"] == "sprzedawca"
    filter2 = employees_df["data_zatrudnienia"] <= transaction_dates_sell[i]
    filter3 = pd.notna(employees_df["data_zwolnienia"])
    filter4 = employees_df["data_zwolnienia"] < transaction_dates_sell[i]
    sell_employee_id[i] = np.random.choice(employees_df['id'][filter1 & filter2 & ~(filter3 & filter4)])

In [91]:
service_employee_id = np.zeros(len(transaction_dates_service))

for i in range(len(transaction_dates_service)):
    filter1 = employees_df["stanowisko"] == "mechanik"
    filter2 = employees_df["data_zatrudnienia"] <= transaction_dates_service[i]
    filter3 = pd.notna(employees_df["data_zwolnienia"])
    filter4 = employees_df["data_zwolnienia"] < transaction_dates_service[i]
    service_employee_id[i] = np.random.choice(employees_df['id'][filter1 & filter2 & ~(filter3 & filter4)])


# klienci

In [92]:
year_lims = [1970, 2010]
transaction_counter = Counter(client_ids)

clients_df = pd.DataFrame(columns=["id", "imię", "nazwisko", "data_urodzenia", "płeć", "PESEL", "miasto", "adres", "karta_lojalnościowa", "telefon", "email"])
unique_clients = np.unique(client_ids)
for i in range(len(unique_clients)):
    if np.random.rand() <= 0.5: # chłop probability
        id_ = unique_clients[i]
        first_name, last_name = random_name_man()
        pesel, birth_date = random_pesel_date_man(year_lims)
        sex = "M"
        city = random_city()
        address = random_street()
        if transaction_counter[id_] >= 3:
            loyalty_card = True
        else:
            loyalty_card = False
        phone = random_phone()
        email = random_email(first_name, last_name, birth_date[-4:])
        clients_df.loc[i] = [unique_clients[i], first_name, last_name, birth_date, sex, pesel, city, address, loyalty_card, phone, email]
    else:
        id_ = unique_clients[i]
        first_name, last_name = random_name_woman()
        pesel, birth_date = random_pesel_date_woman(year_lims)
        sex = "F"
        city = random_city()
        address = random_street()
        if transaction_counter[id_] >= 3:
            loyalty_card = True
        else:
            loyalty_card = False
        phone = random_phone()
        email = random_email(first_name, last_name, birth_date[-4:])
        clients_df.loc[i] = [unique_clients[i], first_name, last_name, birth_date, sex, pesel, city, address, loyalty_card, phone, email]

In [93]:
clients_df

id       imię    nazwisko data_urodzenia płeć        PESEL   miasto  \
0        1   Elżbieta      Olczak     10/11/1984    F  84111059465  Wrocław   
1        2    Andrzej  Przybylski     01/05/1985    M  85050131634  Wrocław   
2        3    Klaudia   Szalewska     25/01/2006    F  06212528440  Wrocław   
3        4       Maja      Bujwid     18/07/1983    F  83071855005  Wrocław   
4        5     Milena       Pracz     19/08/1979    F  79081926206     Łódź   
...    ...        ...         ...            ...  ...          ...      ...   
1468  1469  Sebastian        Hlib     06/07/1993    M  93070670552  Wrocław   
1469  1470     Maksym     Walczak     14/10/2008    M  08301492032  Wrocław   
1470  1471      Nadia       Broda     14/03/1996    F  96031418646  Wrocław   
1471  1472   Krystyna    Szlendak     04/01/1992    F  92010422989  Wrocław   
1472  1473     Sofiia      Klimko     02/12/1981    F  81120297149  Wrocław   

                            adres  karta_lojalnościowa      telefon  \
0       ul. Stefana Żeromskiego 1                False  48647397737   
1             ul. Spacerowa 29/46                False  48517943508   
2                  ul. Zamkowa 87                False  48041968828   
3                 ul. Emerytów 84                False  48044122383   
4               ul. Wyzwolenia 46                False  48110133381   
...                           ...                  ...          ...   
1468             ul. Dębowa 85/21                False  48816310941   
1469         ul. Inżynierska 87/3                False  48425088767   
1470           ul. Topolowa 16/12                False  48020837207   
1471  ul. Henryka Sienkiewicza 72                False  48114670616   
1472            ul. Miłosza 10/45                False  48369518698   

                        email  
0           olczak1@gmail.com  
1          a.przybylski@o2.pl  
2        szalewska20063@wp.pl  
3        m.bujwid83@gmail.com  
4               prac-@onet.pl  
...                       ...  
1468       sebh1993@gmail.com  
1469   mwalczak1991@gmail.com  
1470            nad.b@onet.pl  
1471     k.szlendak@gmail.com  
1472  sof.klimk1981@gmail.com  

[1473 rows x 11 columns]

In [94]:
np.sum(clients_df['karta_lojalnościowa'])

np.int64(86)

# auta

In [95]:
rng = np.random.default_rng()

data_car, data_bike = get_car_data()
make_list_car, model_list_car, car_weights = get_car_weights()
make_list_bike, model_list_bike, bike_weights = get_bike_weights()

In [96]:
def create_car(i):

    is_car = rng.random() < 0.9
    colors = np.array(('czarny', 'biały', 'szary', 'srebrny', 'niebieski', 'czerwony', 'brązowy', 'złoty', 'żółty', 'inny'))
    colors_weights = np.array((0.22, 0.19, 0.18, 0.15, 0.10, 0.09, 0.03, 0.02, 0.01, 0.01))

    if is_car:
        index = rng.choice(len(make_list_car), p=car_weights)
        make, model = make_list_car[index], model_list_car[index]
        weights = data_car[(data_car['make'] == make) & (data_car['model'] == model)]
        body = np.array(('SUV', 'Hatchback', 'Sedan', 'Kombi', 'Coupe', 'Van', 'Minivan', 'Kabriolet'))
        body_weights = np.array((0.25, 0.25, 0.23, 0.17, 0.06, 0.03, 0.009, 0.001))
    else:
        index = rng.choice(len(make_list_bike), p=bike_weights)
        make, model = make_list_bike[index], model_list_bike[index]
        weights = False
        body = False
        body_weights = False

    wheels = 4 if is_car else 2
    year = get_year()
    gear = get_gear(weights, is_car)
    fuel = get_fuel(weights, is_car)
    post_accident = get_post_accident()
    hp = get_hp(weights, is_car)
    color = get_color(colors, colors_weights)
    body_type = get_body_type(body, body_weights, is_car)
    engine_capacity = get_engine_capacity(hp, is_car)
    doors = get_doors(is_car)
    seats = get_num_of_seats(is_car)
    available = (i+1 not in car_ids_sell and i+1 in car_ids_buy)
    
    return [i+1, make, model, wheels, year, body_type, post_accident, color, fuel, engine_capacity, gear, doors, seats, available]


def create_car_table(n):
    
    df = pd.DataFrame(columns=['id', 'marka', 'model', 'liczba_kół', 'rok_produkcji', 'typ_nadwozia', 'czy_powypadkowy', 'kolor', 'typ_paliwa', 'pojemość_silnika', 'skrzynia_biegów', 'liczba_drzwi', 'liczba_miejsc', 'czy_dostępny'])
    for i in range(n):
        row = create_car(i)
        df.loc[i] = row
    return df


In [97]:
df_samochody = create_car_table(max(car_ids)-1)

In [98]:
df_samochody

id    marka   model  liczba_kół  rok_produkcji typ_nadwozia  \
0      1     Fiat    500C           4           2010          SUV   
1      2     Audi      A3           4           2006    Hatchback   
2      3      BMW     120           4           2008          SUV   
3      4     Ford   Focus           4           2015      Minivan   
4      5    Skoda   Karoq           4           2007    Hatchback   
..   ...      ...     ...         ...            ...          ...   
963  964  Renault  Twingo           4           2013          SUV   
964  965    Skoda   Fabia           4           2007        Sedan   
965  966     Fiat    500X           4           2014    Hatchback   
966  967     Ford  Mondeo           4           2010          SUV   
967  968     SEAT    Leon           4           2011    Hatchback   

     czy_powypadkowy      kolor typ_paliwa  pojemość_silnika skrzynia_biegów  \
0              False    srebrny    Benzyna               1.0        Manualna   
1              False    srebrny     Diesel               3.0        Manualna   
2              False      biały     Diesel               2.8        Manualna   
3              False    srebrny     Diesel               1.9        Manualna   
4              False   czerwony    Benzyna               2.5    Automatyczna   
..               ...        ...        ...               ...             ...   
963            False      biały    Benzyna               1.3        Manualna   
964            False      szary    Benzyna               0.9        Manualna   
965            False      szary    Benzyna               1.8    Automatyczna   
966            False     czarny     Diesel               2.7    Automatyczna   
967            False  niebieski    Benzyna               2.3        Manualna   

     liczba_drzwi  liczba_miejsc  czy_dostępny  
0               5              5         False  
1               5              5         False  
2               5              5         False  
3               5              5         False  
4               5              5         False  
..            ...            ...           ...  
963             3              5         False  
964             3              2         False  
965             5              5          True  
966             3              5          True  
967             5              5          True  

[968 rows x 14 columns]

# Usługi

In [99]:
print(len(transaction_dates_service))
print(len(car_ids_service))
print(len(client_ids_service))
service_employee = rng.choice(employees_df[employees_df['stanowisko'] == 'mechanik']['id'], len(car_ids_service))
service_price = rng.random(size=len(car_ids_service))
service_ids = np.arange(len(transaction_dates_service)) + 1

125
125
125


In [100]:
df_services = pd.DataFrame()
df_services['id'] = service_ids
df_services['id_samochodu'] = car_ids_service
df_services['id_klienta'] = client_ids_service
df_services['id_pracownika'] = service_employee
df_services['cena'] = service_price # to trzeb apóźniej uzależnić od użytych części
df_services['data_zaksiegowania'] = transaction_dates_service

In [101]:
df_services

id  id_samochodu  id_klienta  id_pracownika      cena data_zaksiegowania
0      1            25          49              9  0.636718         2014-03-07
1      2            27          51             10  0.060897         2014-03-08
2      3            34          65              4  0.886440         2014-03-19
3      4            39          73              4  0.649767         2014-04-01
4      5            42          78              4  0.287767         2014-04-06
..   ...           ...         ...            ...       ...                ...
120  121           944        1446              4  0.829048         2020-10-20
121  122           945        1448              9  0.441356         2020-10-22
122  123           947        1450              4  0.561258         2020-10-25
123  124           948        1451              4  0.889984         2020-10-29
124  125           960        1110              4  0.827066         2020-11-20

[125 rows x 6 columns]

# Użyte części

In [102]:
data_parts = get_data_parts()
data_parts_filtered = data_parts[data_parts['motor'] == True]

def get_parts_indexes(car_id):
    if df_samochody.loc[car_id-1].values[3] == 2:
        parts_set = data_parts_filtered[['id','część']]
    else:
        parts_set = data_parts[['id','część']]
    
    parts_indexes = parts_set['id']
    num_parts = rng.choice([1, 2, 3], p=[0.6, 0.3, 0.1])
    indexes = rng.choice(parts_indexes, size=num_parts)
    return indexes

for i in car_ids_service:
    print(get_parts_indexes(i))

[52 19 45]
[30 11]
[19 15]
[25]
[20]
[35]
[32 52]
[50]
[49 20 25]
[56 63]
[63 58]
[3]
[24 49]
[30]
[33]
[20]
[9]
[59  0]
[25]
[21]
[43 38]
[22 46]
[27]
[ 8 41]
[21]
[6]
[39]
[2]
[23]
[14]
[46  6]
[14 37]
[45]
[29]
[21]
[28 35]
[13]
[40]
[42]
[22]
[24]
[56]
[3]
[15 60]
[61]
[42]
[33 48]
[ 2 26]
[43]
[24]
[56]
[43 24]
[25 36]
[24]
[ 7 14]
[18]
[5]
[34]
[29]
[ 5 31]
[2]
[60 53]
[18]
[7]
[13]
[8]
[19  9]
[30 10 27]
[19]
[55 46]
[48]
[28]
[61]
[46  9]
[15]
[62 59]
[46 52]
[18 46 55]
[14 21 22]
[51 49]
[22]
[34]
[ 9 41 39]
[10]
[59]
[21]
[24]
[21]
[45 50]
[5]
[ 7 46]
[12]
[36]
[41]
[54  8]
[55 57]
[16 35]
[49  8]
[12]
[41]
[25]
[44 19]
[ 1 27]
[26]
[4 2]
[2]
[52]
[43  1]
[11]
[55]
[19 42]
[32 16]
[62]
[45]
[29]
[ 9 63 54]
[41 58 12]
[15]
[ 2 18]
[24  5  6]
[62]
[63]
[2 3]
[53]
[61]
